In [1]:
import pandas as pd

In [13]:
data= pd.read_excel('./../../Donnees_Brutes_Declaration_Ruches_2017.xlsx', sheet_name = 2)

In [14]:
data.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Exemple de lecture : les déclarations de ruches de 8 colonies représentent un total de 408 colonies dans le département de l'Ain pendant la période obligatoire 2017.,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 420,Unnamed: 421,Unnamed: 422,Unnamed: 423,Unnamed: 424,Unnamed: 425,Unnamed: 426,Unnamed: 427,Unnamed: 428,Unnamed: 429
0,SIRET,(Tous),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TCD2,Total de colonies par nombre de colonies décla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Département,0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,485.0,487.0,488.0,490.0,492.0,494.0,495.0,500 - 999,⩾ 1000,Total général
4,01,0,57.0,162.0,204.0,296.0,335.0,324.0,245.0,408.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3462,NaN,19013
5,02,0,16.0,84.0,60.0,108.0,105.0,120.0,126.0,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5735
6,03,0,48.0,98.0,150.0,168.0,205.0,132.0,161.0,192.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1437,NaN,6768
7,04,0,9.0,46.0,51.0,124.0,120.0,66.0,49.0,168.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3682,1150,31941
8,05,0,20.0,66.0,93.0,120.0,185.0,156.0,140.0,208.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,552,NaN,17215
9,06,0,44.0,116.0,147.0,136.0,245.0,174.0,133.0,192.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,625,1088,13388
10,07,0,44.0,124.0,126.0,184.0,240.0,174.0,217.0,272.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3460,NaN,24956
11,08,0,17.0,44.0,69.0,128.0,130.0,114.0,119.0,168.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,595,NaN,6347
12,09,0,8.0,28.0,42.0,76.0,95.0,48.0,77.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550,1160,14544
13,10,0,16.0,34.0,33.0,56.0,125.0,54.0,112.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6802
14,11,0,18.0,60.0,60.0,80.0,145.0,72.0,70.0,152.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3540,1196,15649
15,12,0,27.0,128.0,168.0,232.0,205.0,192.0,196.0,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3637,8350,24987
16,13,0,60.0,156.0,201.0,220.0,335.0,306.0,161.0,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4376,3110,28503
17,14,0,55.0,124.0,135.0,212.0,150.0,180.0,161.0,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1183,NaN,6481
18,15,0,21.0,60.0,75.0,120.0,120.0,78.0,70.0,104.0,...,485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8078
19,16,NaN,22.0,54.0,75.0,100.0,110.0,84.0,105.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750,1500,10727